### ISSUE TITLE
feat: 바이낸스와 업비트에서 특정 티커의 가격을 실시간으로 얻어오는 기능 추가

### ISSUE THREAD

**Issue by jemin7709** [jemin7709/ToTheMoon#1]
## Background
* 바이낸스와 업비트에서 지원하는 티커의 가격을 얻어오는 기능은 별도의 API를 사용해야 함
* 이를 하나로 합쳐 사용 편의성을 높이고자 함

## Todo
- [x] pyupbit, ccxt 라이브러리를 활용하여 업비트와 바이낸스에서 실시간으로 티커 가격을 얻어오는 기능 구현
- [x] multiprocessing 라이브러리를 사용하여 데이터를 병렬적으로 처리하도록 구현
- [x] PriceFetcher 클래스를 구현하여 티커 리스트를 받아서 해당 티커들의 가격 정보를 실시간으로 업데이트 하도록 구현
